name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup pnpm and Node.js
      uses: pnpm/setup@v2
      with:
        version: ^11
        install: false
        cache: true

    - name: Install dependencies
      run: pnpm ci
    
    - name: Build
      run: pnpm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        path: ./dist
        name: dist
