name: Lint

on:
  push:
    branches:
      - fork/master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lint: [lint, typecheck]

    steps:
    - uses: actions/checkout@v7

    - name: Setup pnpm and Node.js
      uses: pnpm/setup@v2
      with:
        version: ^11
        install: false
        cache: true

    - name: Install dependencies
      run: pnpm ci

    - name: Run ${{ matrix.lint }}
      run: |
        pnpm run ${{ matrix.lint }}
