name: Test

on:
  push:
    branches:
      - fork/master
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: [build]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        os: [ubuntu-latest]
        include:
          - node-version: 18.x
            allow-failure: true
          - node-version: 24.x
            os: windows-latest
            allow-failure: true

    steps:
    - uses: actions/checkout@v7

    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        version: ^11
        run_install: false

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm ci

    # NOTE: pnpm test always use node which defined on devEngines in package.json, so not apply matrix.node-version.
    - name: Run tests
      run: |
        pnpm run test
      continue-on-error: ${{ matrix.allow-failure || false }}

    - name: Download build artifact
      uses: actions/download-artifact@v8
      with:
        name: dist
        path: ./dist

    - name: Run CLI commands
      run: |
        node ./dist/index.js keygen ./test --force
        node ./dist/index.js pack ./test/myFirstExtension -p ./test/key.pem -o test.crx
        node ./dist/index.js pack ./test/myFirstExtension --zip-output test.zip
