name: Test

on:
  push:
    branches:
      - fork/master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        os: [ubuntu-latest]
        include:
          - node-version: 18.x
            allow-failure: true
          - node-version: 24.x
            os: windows-latest
            allow-failure: true

    steps:
    - uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ^10
        run_install: false

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Override install rolldown in node 18
      if: matrix.node-version == '18.x'
      run: |
        ROLLDOWNBINDING=@rolldown/binding-linux-x64-gnu@$( \
          pnpm list @rolldown/binding-linux-x64-gnu --depth Infinity --parseable \
          | grep @rolldown+binding-linux-x64-gnu \
          | sed 's/.*[\\\/]@rolldown+binding-linux-x64-gnu@\(.*\)[\\\/]node_modules.*/\1/' \
        )
        echo "$ROLLDOWNBINDING"
        pnpm add -D $ROLLDOWNBINDING

    - name: Run tests
      run: |
        tree node_modules/.pnpm/ | grep @rolldown+binding
        pnpm test
      continue-on-error: ${{ matrix.allow-failure || false }}

    - name: Run CLI commands
      run: |
        pnpm build

        node ./dist/index.js keygen ./test --force
        node ./dist/index.js pack ./test/myFirstExtension -p ./test/key.pem -o test.crx
        node ./dist/index.js pack ./test/myFirstExtension --zip-output test.zip
